command = """/setblock ~1 62 ~7 stone_slab    
                /setblock ~1 62 ~8 stone_slab    
                /setblock ~1 62 ~9 stone_slab    
                /setblock ~1 62 ~10 stone_slab    
                /setblock ~1 62 ~11 stone_slab    
                /setblock ~1 62 ~12 stone_slab    
                /setblock ~1 62 ~13 stone_slab    
                /setblock ~1 62 ~14 stone_slab    
                /setblock ~1 62 ~15 stone_slab    
                /setblock ~1 62 ~16 stone_slab    
                /setblock ~1 62 ~17 stone_slab    
                /setblock ~1 62 ~18 stone_slab    
                /setblock ~1 62 ~19 stone_slab    
                /setblock ~2 62 ~7 stone_slab    
                /setblock ~2 62 ~8 log    
                /setblock ~2 62 ~9 cobblestone    
                /setblock ~2 62 ~10 cobblestone    
                /setblock ~2 62 ~11 cobblestone    
                /setblock ~2 62 ~12 cobblestone    
                /setblock ~2 62 ~13 cobblestone    
                /setblock ~2 62 ~14 log    
                /setblock ~2 62 ~15 cobblestone    
                /setblock ~2 62 ~16 cobblestone    
                /setblock ~2 62 ~17 cobblestone    
                /setblock ~2 62 ~18 log    
                /setblock ~2 62 ~19 stone_slab    
                /setblock ~3 62 ~7 stone_slab    
                /setblock ~3 62 ~8 cobblestone    
                /setblock ~3 62 ~9 wool    
                /setblock ~3 62 ~10 wool    
                /setblock ~3 62 ~11 wool    
                /setblock ~3 62 ~12 grass    
                /setblock ~3 62 ~13 planks    
                /setblock ~3 62 ~14 cobblestone    
                /setblock ~3 62 ~16 planks    
                /setblock ~3 62 ~17 planks    
                /setblock ~3 62 ~18 cobblestone    
                /setblock ~3 62 ~19 stone_slab    
                /setblock ~4 62 ~2 log    
                /setblock ~4 62 ~7 stone_slab    
                /setblock ~4 62 ~8 log    
                /setblock ~4 62 ~9 wool    
                /setblock ~4 62 ~10 wool    
                /setblock ~4 62 ~11 wool    
                /setblock ~4 62 ~12 grass    
                /setblock ~4 62 ~13 planks    
                /setblock ~4 62 ~14 planks    
                /setblock ~4 62 ~15 planks    
                /setblock ~4 62 ~16 planks    
                /setblock ~4 62 ~17 planks    
                /setblock ~4 62 ~18 cobblestone    
                /setblock ~4 62 ~19 stone_slab    
                /setblock ~5 62 ~7 stone_slab    
                /setblock ~5 62 ~8 cobblestone    
                /setblock ~5 62 ~9 wool    
                /setblock ~5 62 ~10 wool    
                /setblock ~5 62 ~11 wool    
                /setblock ~5 62 ~12 grass    
                /setblock ~5 62 ~13 planks    
                /setblock ~5 62 ~14 cobblestone    
                /setblock ~5 62 ~15 planks    
                /setblock ~5 62 ~16 planks    
                /setblock ~5 62 ~17 planks    
                /setblock ~5 62 ~18 cobblestone    
                /setblock ~5 62 ~19 stone_slab    
                /setblock ~6 62 ~7 grass    
                /setblock ~6 62 ~8 stonebrick    
                /setblock ~6 62 ~9 wool    
                /setblock ~6 62 ~10 wool    
                /setblock ~6 62 ~11 wool    
                /setblock ~6 62 ~12 planks    
                /setblock ~6 62 ~13 planks    
                /setblock ~6 62 ~14 log    
                /setblock ~6 62 ~15 cobblestone    
                /setblock ~6 62 ~16 cobblestone    
                /setblock ~6 62 ~17 cobblestone    
                /setblock ~6 62 ~18 log    
                /setblock ~6 62 ~19 stone_slab    
                /setblock ~7 62 ~7 stone_slab    
                /setblock ~7 62 ~8 cobblestone    
                /setblock ~7 62 ~9 wool    
                /setblock ~7 62 ~10 wool    
                /setblock ~7 62 ~11 wool    
                /setblock ~7 62 ~12 wool    
                /setblock ~7 62 ~13 wool    
                /setblock ~7 62 ~14 cobblestone    
                /setblock ~7 62 ~15 stone_slab    
                /setblock ~7 62 ~16 stone_slab    
                /setblock ~7 62 ~17 stone_slab    
                /setblock ~7 62 ~18 stone_slab    
                /setblock ~7 62 ~19 stone_slab    
                /setblock ~8 62 ~2 log    
                /setblock ~8 62 ~7 stone_slab    
                /setblock ~8 62 ~8 log    
                /setblock ~8 62 ~9 wool    
                /setblock ~8 62 ~10 wool    
                /setblock ~8 62 ~11 wool    
                /setblock ~8 62 ~12 stonebrick    
                /setblock ~8 62 ~13 stonebrick    
                /setblock ~8 62 ~14 cobblestone    
                /setblock ~8 62 ~15 stone_slab    
                /setblock ~9 62 ~7 stone_slab    
                /setblock ~9 62 ~8 cobblestone    
                /setblock ~9 62 ~9 wool    
                /setblock ~9 62 ~10 wool    
                /setblock ~9 62 ~11 wool    
                /setblock ~9 62 ~12 stonebrick    
                /setblock ~9 62 ~13 netherrack    
                /setblock ~9 62 ~14 cobblestone    
                /setblock ~9 62 ~15 stone_slab    
                /setblock ~10 62 ~7 stone_slab    
                /setblock ~10 62 ~8 log    
                /setblock ~10 62 ~9 cobblestone    
                /setblock ~10 62 ~10 cobblestone    
                /setblock ~10 62 ~11 cobblestone    
                /setblock ~10 62 ~12 cobblestone    
                /setblock ~10 62 ~13 cobblestone    
                /setblock ~10 62 ~14 log    
                /setblock ~10 62 ~15 stone_slab    
                /setblock ~11 62 ~7 stone_slab    
                /setblock ~11 62 ~8 stone_slab    
                /setblock ~11 62 ~9 stone_slab    
                /setblock ~11 62 ~10 stone_slab    
                /setblock ~11 62 ~11 stone_slab    
                /setblock ~11 62 ~12 stone_slab    
                /setblock ~11 62 ~13 stone_slab    
                /setblock ~11 62 ~14 stone_slab    
                /setblock ~11 62 ~15 stone_slab    
                /setblock ~2 63 ~8 log    
                /setblock ~2 63 ~9 cobblestone    
                /setblock ~2 63 ~10 cobblestone    
                /setblock ~2 63 ~11 cobblestone    
                /setblock ~2 63 ~12 cobblestone    
                /setblock ~2 63 ~13 cobblestone    
                /setblock ~2 63 ~14 log    
                /setblock ~2 63 ~15 cobblestone    
                /setblock ~2 63 ~16 cobblestone    
                /setblock ~2 63 ~17 cobblestone    
                /setblock ~2 63 ~18 log    
                /setblock ~3 63 ~8 cobblestone    
                /setblock ~3 63 ~9 grass    
                /setblock ~3 63 ~12 planks    
                /setblock ~3 63 ~13 grass    
                /setblock ~3 63 ~14 cobblestone    
                /setblock ~3 63 ~15 grass    
                /setblock ~3 63 ~17 grass    
                /setblock ~3 63 ~18 cobblestone    
                /setblock ~4 63 ~2 log    
                /setblock ~4 63 ~8 log    
                /setblock ~4 63 ~9 dark_oak_fence    
                /setblock ~4 63 ~12 planks    
                /setblock ~4 63 ~14 grass    
                /setblock ~4 63 ~17 grass    
                /setblock ~4 63 ~18 cobblestone    
                /setblock ~5 63 ~8 cobblestone    
                /setblock ~5 63 ~9 grass    
                /setblock ~5 63 ~12 planks    
                /setblock ~5 63 ~14 cobblestone    
                /setblock ~5 63 ~17 grass    
                /setblock ~5 63 ~18 cobblestone    
                /setblock ~6 63 ~8 grass    
                /setblock ~6 63 ~12 planks    
                /setblock ~6 63 ~14 log    
                /setblock ~6 63 ~15 cobblestone    
                /setblock ~6 63 ~16 cobblestone    
                /setblock ~6 63 ~17 cobblestone    
                /setblock ~6 63 ~18 log    
                /setblock ~7 63 ~8 cobblestone    
                /setblock ~7 63 ~9 grass    
                /setblock ~7 63 ~14 cobblestone    
                /setblock ~8 63 ~2 log    
                /setblock ~8 63 ~8 log    
                /setblock ~8 63 ~9 dark_oak_fence    
                /setblock ~8 63 ~12 grass    
                /setblock ~8 63 ~13 grass    
                /setblock ~8 63 ~14 cobblestone    
                /setblock ~9 63 ~8 cobblestone    
                /setblock ~9 63 ~9 grass    
                /setblock ~9 63 ~11 noteblock    
                /setblock ~9 63 ~12 grass    
                /setblock ~9 63 ~13 grass    
                /setblock ~9 63 ~14 cobblestone    
                /setblock ~10 63 ~8 log    
                /setblock ~10 63 ~9 cobblestone    
                /setblock ~10 63 ~10 cobblestone    
                /setblock ~10 63 ~11 cobblestone    
                /setblock ~10 63 ~12 cobblestone    
                /setblock ~10 63 ~13 cobblestone    
                /setblock ~10 63 ~14 log    
                /setblock ~2 64 ~8 log    
                /setblock ~2 64 ~9 cobblestone    
                /setblock ~2 64 ~10 cobblestone    
                /setblock ~2 64 ~11 glass    
                /setblock ~2 64 ~12 cobblestone    
                /setblock ~2 64 ~13 cobblestone    
                /setblock ~2 64 ~14 log    
                /setblock ~2 64 ~15 cobblestone    
                /setblock ~2 64 ~16 cobblestone    
                /setblock ~2 64 ~17 cobblestone    
                /setblock ~2 64 ~18 log    
                /setblock ~3 64 ~8 glass    
                /setblock ~3 64 ~10 grass    
                /setblock ~3 64 ~12 grass    
                /setblock ~3 64 ~13 grass    
                /setblock ~3 64 ~14 cobblestone    
                /setblock ~3 64 ~16 grass    
                /setblock ~3 64 ~18 cobblestone    
                /setblock ~3 64 ~19 grass    
                /setblock ~4 64 ~2 log    
                /setblock ~4 64 ~7 grass    
                /setblock ~4 64 ~8 log    
                /setblock ~4 64 ~9 grass    
                /setblock ~4 64 ~12 grass    
                /setblock ~4 64 ~14 grass    
                /setblock ~4 64 ~18 glass    
                /setblock ~5 64 ~8 cobblestone    
                /setblock ~5 64 ~12 grass    
                /setblock ~5 64 ~14 cobblestone    
                /setblock ~5 64 ~17 stonebrick    
                /setblock ~5 64 ~18 cobblestone    
                /setblock ~6 64 ~8 grass    
                /setblock ~6 64 ~12 dark_oak_fence    
                /setblock ~6 64 ~14 log    
                /setblock ~6 64 ~15 cobblestone    
                /setblock ~6 64 ~16 cobblestone    
                /setblock ~6 64 ~17 cobblestone    
                /setblock ~6 64 ~18 log    
                /setblock ~7 64 ~8 cobblestone    
                /setblock ~7 64 ~14 cobblestone    
                /setblock ~8 64 ~2 log    
                /setblock ~8 64 ~7 grass    
                /setblock ~8 64 ~8 log    
                /setblock ~8 64 ~9 grass    
                /setblock ~8 64 ~14 cobblestone    
                /setblock ~9 64 ~8 glass    
                /setblock ~9 64 ~14 cobblestone    
                /setblock ~10 64 ~8 log    
                /setblock ~10 64 ~9 cobblestone    
                /setblock ~10 64 ~10 cobblestone    
                /setblock ~10 64 ~11 cobblestone    
                /setblock ~10 64 ~12 cobblestone    
                /setblock ~10 64 ~13 cobblestone    
                /setblock ~10 64 ~14 log    
                /setblock ~2 65 ~8 log    
                /setblock ~2 65 ~9 cobblestone    
                /setblock ~2 65 ~10 cobblestone    
                /setblock ~2 65 ~11 cobblestone    
                /setblock ~2 65 ~12 cobblestone    
                /setblock ~2 65 ~13 cobblestone    
                /setblock ~2 65 ~14 log    
                /setblock ~2 65 ~15 cobblestone    
                /setblock ~2 65 ~16 cobblestone    
                /setblock ~2 65 ~17 cobblestone    
                /setblock ~2 65 ~18 log    
                /setblock ~3 65 ~8 cobblestone    
                /setblock ~3 65 ~11 grass    
                /setblock ~3 65 ~12 planks    
                /setblock ~3 65 ~13 grass    
                /setblock ~3 65 ~14 cobblestone    
                /setblock ~3 65 ~18 cobblestone    
                /setblock ~4 65 ~2 log    
                /setblock ~4 65 ~8 log    
                /setblock ~4 65 ~11 grass    
                /setblock ~4 65 ~12 planks    
                /setblock ~4 65 ~14 cobblestone    
                /setblock ~4 65 ~18 cobblestone    
                /setblock ~5 65 ~8 cobblestone    
                /setblock ~5 65 ~11 grass    
                /setblock ~5 65 ~12 planks    
                /setblock ~5 65 ~14 cobblestone    
                /setblock ~5 65 ~17 stonebrick    
                /setblock ~5 65 ~18 cobblestone    
                /setblock ~6 65 ~8 cobblestone    
                /setblock ~6 65 ~12 planks    
                /setblock ~6 65 ~13 planks    
                /setblock ~6 65 ~14 log    
                /setblock ~6 65 ~15 cobblestone    
                /setblock ~6 65 ~16 cobblestone    
                /setblock ~6 65 ~17 cobblestone    
                /setblock ~6 65 ~18 log    
                /setblock ~7 65 ~8 cobblestone    
                /setblock ~7 65 ~14 cobblestone    
                /setblock ~8 65 ~2 log    
                /setblock ~8 65 ~8 log    
                /setblock ~8 65 ~12 grass    
                /setblock ~8 65 ~13 grass    
                /setblock ~8 65 ~14 cobblestone    
                /setblock ~9 65 ~8 cobblestone    
                /setblock ~9 65 ~12 grass    
                /setblock ~9 65 ~13 stonebrick    
                /setblock ~9 65 ~14 cobblestone    
                /setblock ~10 65 ~8 log    
                /setblock ~10 65 ~9 cobblestone    
                /setblock ~10 65 ~10 cobblestone    
                /setblock ~10 65 ~11 cobblestone    
                /setblock ~10 65 ~12 cobblestone    
                /setblock ~10 65 ~13 cobblestone    
                /setblock ~10 65 ~14 log    
                /setblock ~1 66 ~7 grass    
                /setblock ~1 66 ~15 planks    
                /setblock ~1 66 ~16 grass    
                /setblock ~1 66 ~17 grass    
                /setblock ~1 66 ~18 grass    
                /setblock ~1 66 ~19 grass    
                /setblock ~2 66 ~7 grass    
                /setblock ~2 66 ~8 log    
                /setblock ~2 66 ~9 log    
                /setblock ~2 66 ~10 log    
                /setblock ~2 66 ~11 log    
                /setblock ~2 66 ~12 log    
                /setblock ~2 66 ~13 log    
                /setblock ~2 66 ~14 log    
                /setblock ~2 66 ~15 log    
                /setblock ~2 66 ~16 log    
                /setblock ~2 66 ~17 log    
                /setblock ~2 66 ~18 log    
                /setblock ~3 66 ~1 grass    
                /setblock ~3 66 ~2 grass    
                /setblock ~3 66 ~3 grass    
                /setblock ~3 66 ~4 grass    
                /setblock ~3 66 ~5 grass    
                /setblock ~3 66 ~6 grass    
                /setblock ~3 66 ~7 planks    
                /setblock ~3 66 ~8 log    
                /setblock ~3 66 ~9 planks    
                /setblock ~3 66 ~10 planks    
                /setblock ~3 66 ~11 grass    
                /setblock ~3 66 ~13 grass    
                /setblock ~3 66 ~14 planks    
                /setblock ~3 66 ~15 planks    
                /setblock ~3 66 ~16 planks    
                /setblock ~3 66 ~17 planks    
                /setblock ~3 66 ~18 log    
                /setblock ~4 66 ~2 log    
                /setblock ~4 66 ~3 log    
                /setblock ~4 66 ~4 log    
                /setblock ~4 66 ~5 log    
                /setblock ~4 66 ~6 log    
                /setblock ~4 66 ~7 log    
                /setblock ~4 66 ~8 log    
                /setblock ~4 66 ~9 planks    
                /setblock ~4 66 ~10 planks    
                /setblock ~4 66 ~11 planks    
                /setblock ~4 66 ~12 planks    
                /setblock ~4 66 ~13 planks    
                /setblock ~4 66 ~14 planks    
                /setblock ~4 66 ~15 planks    
                /setblock ~4 66 ~16 planks    
                /setblock ~4 66 ~17 planks    
                /setblock ~4 66 ~18 log    
                /setblock ~5 66 ~2 log    
                /setblock ~5 66 ~3 planks    
                /setblock ~5 66 ~4 planks    
                /setblock ~5 66 ~5 planks    
                /setblock ~5 66 ~6 planks    
                /setblock ~5 66 ~7 planks    
                /setblock ~5 66 ~8 planks    
                /setblock ~5 66 ~9 planks    
                /setblock ~5 66 ~10 planks    
                /setblock ~5 66 ~11 planks    
                /setblock ~5 66 ~12 planks    
                /setblock ~5 66 ~13 planks    
                /setblock ~5 66 ~14 planks    
                /setblock ~5 66 ~15 planks    
                /setblock ~5 66 ~16 planks    
                /setblock ~5 66 ~17 stonebrick    
                /setblock ~5 66 ~18 log    
                /setblock ~6 66 ~2 log    
                /setblock ~6 66 ~3 planks    
                /setblock ~6 66 ~4 planks    
                /setblock ~6 66 ~5 planks    
                /setblock ~6 66 ~6 planks    
                /setblock ~6 66 ~7 planks    
                /setblock ~6 66 ~8 planks    
                /setblock ~6 66 ~9 planks    
                /setblock ~6 66 ~10 planks    
                /setblock ~6 66 ~11 planks    
                /setblock ~6 66 ~12 planks    
                /setblock ~6 66 ~13 planks    
                /setblock ~6 66 ~14 log    
                /setblock ~6 66 ~15 log    
                /setblock ~6 66 ~16 log    
                /setblock ~6 66 ~17 log    
                /setblock ~6 66 ~18 log    
                /setblock ~7 66 ~2 log    
                /setblock ~7 66 ~3 planks    
                /setblock ~7 66 ~4 planks    
                /setblock ~7 66 ~5 planks    
                /setblock ~7 66 ~6 planks    
                /setblock ~7 66 ~7 planks    
                /setblock ~7 66 ~8 planks    
                /setblock ~7 66 ~9 planks    
                /setblock ~7 66 ~10 planks    
                /setblock ~7 66 ~11 planks    
                /setblock ~7 66 ~12 planks    
                /setblock ~7 66 ~13 planks    
                /setblock ~7 66 ~14 log    
                /setblock ~7 66 ~15 planks    
                /setblock ~7 66 ~16 grass    
                /setblock ~7 66 ~17 grass    
                /setblock ~7 66 ~18 grass    
                /setblock ~7 66 ~19 grass    
                /setblock ~8 66 ~2 log    
                /setblock ~8 66 ~3 log    
                /setblock ~8 66 ~4 log    
                /setblock ~8 66 ~5 log    
                /setblock ~8 66 ~6 log    
                /setblock ~8 66 ~7 log    
                /setblock ~8 66 ~8 log    
                /setblock ~8 66 ~9 planks    
                /setblock ~8 66 ~10 planks    
                /setblock ~8 66 ~11 planks    
                /setblock ~8 66 ~12 planks    
                /setblock ~8 66 ~13 planks    
                /setblock ~8 66 ~14 log    
                /setblock ~8 66 ~15 grass    
                /setblock ~9 66 ~1 grass    
                /setblock ~9 66 ~2 grass    
                /setblock ~9 66 ~3 grass    
                /setblock ~9 66 ~4 grass    
                /setblock ~9 66 ~5 grass    
                /setblock ~9 66 ~6 grass    
                /setblock ~9 66 ~7 planks    
                /setblock ~9 66 ~8 log    
                /setblock ~9 66 ~9 planks    
                /setblock ~9 66 ~10 planks    
                /setblock ~9 66 ~11 planks    
                /setblock ~9 66 ~12 planks    
                /setblock ~9 66 ~13 stonebrick    
                /setblock ~9 66 ~14 log    
                /setblock ~9 66 ~15 grass    
                /setblock ~10 66 ~7 grass    
                /setblock ~10 66 ~8 log    
                /setblock ~10 66 ~9 log    
                /setblock ~10 66 ~10 log    
                /setblock ~10 66 ~11 log    
                /setblock ~10 66 ~12 log    
                /setblock ~10 66 ~13 log    
                /setblock ~10 66 ~14 log    
                /setblock ~10 66 ~15 grass    
                /setblock ~11 66 ~7 grass    
                /setblock ~11 66 ~15 grass    
                /setblock ~1 67 ~8 grass    
                /setblock ~1 67 ~14 grass    
                /setblock ~2 67 ~8 grass    
                /setblock ~2 67 ~9 grass    
                /setblock ~2 67 ~10 grass    
                /setblock ~2 67 ~11 grass    
                /setblock ~2 67 ~12 grass    
                /setblock ~2 67 ~13 grass    
                /setblock ~2 67 ~14 planks    
                /setblock ~2 67 ~15 grass    
                /setblock ~2 67 ~16 grass    
                /setblock ~2 67 ~17 grass    
                /setblock ~2 67 ~18 grass    
                /setblock ~2 67 ~19 grass    
                /setblock ~3 67 ~8 grass    
                /setblock ~3 67 ~9 planks    
                /setblock ~3 67 ~18 grass    
                /setblock ~4 67 ~1 grass    
                /setblock ~4 67 ~2 grass    
                /setblock ~4 67 ~3 grass    
                /setblock ~4 67 ~4 grass    
                /setblock ~4 67 ~5 grass    
                /setblock ~4 67 ~6 grass    
                /setblock ~4 67 ~7 grass    
                /setblock ~4 67 ~8 planks    
                /setblock ~4 67 ~17 grass    
                /setblock ~4 67 ~18 grass    
                /setblock ~5 67 ~2 grass    
                /setblock ~5 67 ~17 stonebrick    
                /setblock ~5 67 ~18 grass    
                /setblock ~6 67 ~2 grass    
                /setblock ~6 67 ~14 planks    
                /setblock ~6 67 ~15 grass    
                /setblock ~6 67 ~16 grass    
                /setblock ~6 67 ~17 grass    
                /setblock ~6 67 ~18 grass    
                /setblock ~6 67 ~19 grass    
                /setblock ~7 67 ~2 grass    
                /setblock ~7 67 ~14 grass    
                /setblock ~8 67 ~1 grass    
                /setblock ~8 67 ~2 grass    
                /setblock ~8 67 ~3 grass    
                /setblock ~8 67 ~4 grass    
                /setblock ~8 67 ~5 grass    
                /setblock ~8 67 ~6 grass    
                /setblock ~8 67 ~7 grass    
                /setblock ~8 67 ~8 planks    
                /setblock ~8 67 ~12 grass    
                /setblock ~8 67 ~13 grass    
                /setblock ~8 67 ~14 grass    
                /setblock ~9 67 ~8 grass    
                /setblock ~9 67 ~9 planks    
                /setblock ~9 67 ~10 grass    
                /setblock ~9 67 ~11 grass    
                /setblock ~9 67 ~12 grass    
                /setblock ~9 67 ~13 stonebrick    
                /setblock ~9 67 ~14 grass    
                /setblock ~10 67 ~8 grass    
                /setblock ~10 67 ~9 grass    
                /setblock ~10 67 ~10 grass    
                /setblock ~10 67 ~11 grass    
                /setblock ~10 67 ~12 grass    
                /setblock ~10 67 ~13 grass    
                /setblock ~10 67 ~14 grass    
                /setblock ~11 67 ~8 grass    
                /setblock ~11 67 ~14 grass    
                /setblock ~1 68 ~9 grass    
                /setblock ~1 68 ~12 grass    
                /setblock ~1 68 ~13 grass    
                /setblock ~2 68 ~9 grass    
                /setblock ~2 68 ~10 grass    
                /setblock ~2 68 ~11 glass    
                /setblock ~2 68 ~12 grass    
                /setblock ~2 68 ~13 grass    
                /setblock ~3 68 ~9 grass    
                /setblock ~3 68 ~13 planks    
                /setblock ~3 68 ~14 grass    
                /setblock ~3 68 ~15 grass    
                /setblock ~3 68 ~16 grass    
                /setblock ~3 68 ~17 grass    
                /setblock ~3 68 ~18 grass    
                /setblock ~3 68 ~19 grass    
                /setblock ~4 68 ~9 grass    
                /setblock ~4 68 ~17 grass    
                /setblock ~4 68 ~18 grass    
                /setblock ~5 68 ~1 grass    
                /setblock ~5 68 ~2 grass    
                /setblock ~5 68 ~3 grass    
                /setblock ~5 68 ~4 grass    
                /setblock ~5 68 ~5 grass    
                /setblock ~5 68 ~6 grass    
                /setblock ~5 68 ~7 grass    
                /setblock ~5 68 ~8 grass    
                /setblock ~5 68 ~9 planks    
                /setblock ~5 68 ~13 planks    
                /setblock ~5 68 ~14 grass    
                /setblock ~5 68 ~15 grass    
                /setblock ~5 68 ~16 grass    
                /setblock ~5 68 ~17 stonebrick    
                /setblock ~5 68 ~18 grass    
                /setblock ~5 68 ~19 grass    
                /setblock ~6 68 ~2 grass    
                /setblock ~6 68 ~3 grass    
                /setblock ~6 68 ~13 grass    
                /setblock ~7 68 ~1 grass    
                /setblock ~7 68 ~2 grass    
                /setblock ~7 68 ~3 grass    
                /setblock ~7 68 ~4 grass    
                /setblock ~7 68 ~5 grass    
                /setblock ~7 68 ~6 grass    
                /setblock ~7 68 ~7 grass    
                /setblock ~7 68 ~8 grass    
                /setblock ~7 68 ~9 planks    
                /setblock ~7 68 ~13 grass    
                /setblock ~8 68 ~9 grass    
                /setblock ~8 68 ~13 grass    
                /setblock ~9 68 ~9 grass    
                /setblock ~9 68 ~13 stonebrick    
                /setblock ~10 68 ~9 grass    
                /setblock ~10 68 ~10 grass    
                /setblock ~10 68 ~11 glass    
                /setblock ~10 68 ~12 grass    
                /setblock ~10 68 ~13 grass    
                /setblock ~11 68 ~9 grass    
                /setblock ~11 68 ~12 grass    
                /setblock ~11 68 ~13 grass    
                /setblock ~1 69 ~10 grass    
                /setblock ~1 69 ~12 grass    
                /setblock ~2 69 ~10 grass    
                /setblock ~2 69 ~11 grass    
                /setblock ~2 69 ~12 grass    
                /setblock ~3 69 ~10 grass    
                /setblock ~3 69 ~12 grass    
                /setblock ~4 69 ~10 grass    
                /setblock ~4 69 ~12 grass    
                /setblock ~4 69 ~13 grass    
                /setblock ~4 69 ~14 grass    
                /setblock ~4 69 ~15 grass    
                /setblock ~4 69 ~16 grass    
                /setblock ~4 69 ~17 grass    
                /setblock ~4 69 ~18 grass    
                /setblock ~4 69 ~19 grass    
                /setblock ~5 69 ~10 grass    
                /setblock ~5 69 ~12 grass    
                /setblock ~5 69 ~17 stonebrick    
                /setblock ~6 69 ~1 grass    
                /setblock ~6 69 ~2 grass    
                /setblock ~6 69 ~3 grass    
                /setblock ~6 69 ~4 grass    
                /setblock ~6 69 ~5 grass    
                /setblock ~6 69 ~6 grass    
                /setblock ~6 69 ~7 grass    
                /setblock ~6 69 ~8 grass    
                /setblock ~6 69 ~9 grass    
                /setblock ~6 69 ~10 grass    
                /setblock ~6 69 ~12 grass    
                /setblock ~7 69 ~10 grass    
                /setblock ~7 69 ~12 grass    
                /setblock ~8 69 ~10 grass    
                /setblock ~8 69 ~12 grass    
                /setblock ~9 69 ~10 grass    
                /setblock ~9 69 ~12 grass    
                /setblock ~9 69 ~13 stonebrick    
                /setblock ~10 69 ~10 grass    
                /setblock ~10 69 ~11 grass    
                /setblock ~10 69 ~12 grass    
                /setblock ~11 69 ~10 grass    
                /setblock ~11 69 ~12 grass    
                /setblock ~1 70 ~11 grass    
                /setblock ~2 70 ~11 grass    
                /setblock ~3 70 ~11 grass    
                /setblock ~4 70 ~11 grass    
                /setblock ~5 70 ~11 grass    
                /setblock ~5 70 ~17 grass    
                /setblock ~6 70 ~11 grass    
                /setblock ~7 70 ~11 grass    
                /setblock ~8 70 ~11 grass    
                /setblock ~9 70 ~11 grass    
                /setblock ~9 70 ~13 stonebrick    
                /setblock ~10 70 ~11 grass    
                /setblock ~11 70 ~11 grass    
                   
"""

commands =command.splitlines()

from pynput import keyboard
from pynput.keyboard import Key, Controller
import time

keyboard2 = Controller()

def on_press(key):
    print(key)
    
    if key ==  keyboard.Key.enter: 
        pass
        # print('did it')
        # # keyboard.type(Key.backspace)
        # time.sleep(0.5)
        # keyboard2.type('t')
        # time.sleep(0.5)
    elif key == keyboard.Key.page_down: 
        for i in range(len(commands)): 
            time.sleep(0.1)
            keyboard2.type('t')
            time.sleep(0.1)
            keyboard2.type(commands[i])
            keyboard2.press(Key.enter)
            
            time.sleep(0.1)
        
        # keyboard2.type('/ hepp;s')
        # keyboard2.type( )

def on_release(key):
    print('{0} released'.format(
        key))
    if key == keyboard.Key.shift_r:
        # Stop listener
        return False

# Collect events until released
with keyboard.Listener(
        on_press=on_press,
        on_release=on_release) as listener:
    listener.join()

# ...or, in a non-blocking fashion:
listener = keyboard.Listener(
    on_press=on_press,
    on_release=on_release)
listener.start()
